MercenaryLoadoutRegistry = MercenaryLoadoutRegistry or {}
MercenaryLoadoutRegistry.ItemBodyLocation = MercenaryLoadoutRegistry.ItemBodyLocation or {}

local locations = MercenaryLoadoutRegistry.ItemBodyLocation
locations.BeltPouch1 = ItemBodyLocation.register("MercenaryLoadout:BeltPouch1")
locations.BeltPouch2 = ItemBodyLocation.register("MercenaryLoadout:BeltPouch2")
locations.BeltPouch3 = ItemBodyLocation.register("MercenaryLoadout:BeltPouch3")
locations.RigPouchL = ItemBodyLocation.register("MercenaryLoadout:RigPouchL")
locations.RigPouchR = ItemBodyLocation.register("MercenaryLoadout:RigPouchR")
locations.RigMagPanel = ItemBodyLocation.register("MercenaryLoadout:RigMagPanel")
locations.PackTopPouch = ItemBodyLocation.register("MercenaryLoadout:PackTopPouch")
locations.PackSidePouchL = ItemBodyLocation.register("MercenaryLoadout:PackSidePouchL")
locations.PackSidePouchR = ItemBodyLocation.register("MercenaryLoadout:PackSidePouchR")
locations.PackMedBox = ItemBodyLocation.register("MercenaryLoadout:PackMedBox")
locations.PackToolbox = ItemBodyLocation.register("MercenaryLoadout:PackToolbox")
locations.KeyClip = ItemBodyLocation.register("MercenaryLoadout:KeyClip")
locations.ArmPouchL = ItemBodyLocation.register("MercenaryLoadout:ArmPouchL")
locations.ArmPouchR = ItemBodyLocation.register("MercenaryLoadout:ArmPouchR")
locations.ThighPouchL1 = ItemBodyLocation.register("MercenaryLoadout:ThighPouchL1")
locations.ThighPouchL2 = ItemBodyLocation.register("MercenaryLoadout:ThighPouchL2")
locations.ThighPouchR1 = ItemBodyLocation.register("MercenaryLoadout:ThighPouchR1")
locations.ThighPouchR2 = ItemBodyLocation.register("MercenaryLoadout:ThighPouchR2")
